name: Benchmarks

on:
  workflow_dispatch:
    inputs:
      additionalGradleOptions:
        description: 'Additional Gradle options'
        required: false
        default: ''

jobs:
  benchmarks:
    name: Benchmarks

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11 and 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          11
          17

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2

    - name: Run Benchmarks
      uses: gradle/gradle-build-action@v3
      with:
        arguments: '--no-daemon :jarhc-benchmarks:runBenchmarks ${{ github.event.inputs.additionalGradleOptions }}'
        cache-read-only: false
