name: Benchmarks

on:
  workflow_dispatch:
    inputs:
      additionalGradleOptions:
        description: 'Additional Gradle options'
        required: false
        default: ''

jobs:
  benchmarks:
    name: Benchmarks

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11 and 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          11
          17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    - name: Run Benchmarks
      run: './gradlew --no-daemon :jarhc:jmh ${{ github.event.inputs.additionalGradleOptions }}'
