name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    inputs:
      additionalGradleOptions:
        description: 'Additional Gradle options'
        required: false
        default: ''

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Restore SonarQube Cache
      uses: actions/cache@v2
      with:
        path: /home/runner/.sonar/cache
        key: sonarqube-cache

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: 'build sonarqube ${{ github.event.inputs.additionalGradleOptions }}'

    - name: Upload reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: reports
        path: build/reports
        retention-days: 7

    - name: Upload libs
      uses: actions/upload-artifact@v2
      with:
        name: libs
        path: build/libs
        retention-days: 14

    - name: Upload docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: build/docs
        retention-days: 7
