name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    inputs:
      additionalGradleOptions:
        description: 'Additional Gradle options'
        required: false
        default: ''

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: 'build ${{ github.event.inputs.additionalGradleOptions }}'

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: build/libs
