name: Dependency-Check

on:
  schedule:
  - cron: '0 17 * * FRI'
  workflow_dispatch:

jobs:
  dependency-check:
    name: Dependency-Check

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Cache Dependency-Check Data
      uses: actions/cache@v2
      with:
        path: dependency-check
        key: dependency-check-data

    - name: Run Dependency-Check Analysis
      uses: gradle/gradle-build-action@v2
      with:
        arguments: dependencyCheckAnalyze

    - name: Upload report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: reports
        path: build/reports/dependency-check
        retention-days: 7

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      if: github.ref == 'refs/heads/master'
      with:
        sarif_file: build/reports/dependency-check/dependency-check-report.sarif
