name: Release Test

on:
  workflow_dispatch:
    inputs:
      additionalGradleOptions:
        description: 'Additional Gradle options'
        required: false
        default: ''

jobs:
  release-test:
    name: Release Test

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2

    - name: Run Release Test
      uses: gradle/gradle-build-action@v3
      with:
        arguments: '--no-daemon :jarhc-release-test:test ${{ github.event.inputs.additionalGradleOptions }}'
        cache-read-only: false

    - name: Upload report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: reports
        path: jarhc-release-tests/build/reports/tests/test
