name: Release Test

on:
  workflow_dispatch:
    inputs:
      additionalGradleOptions:
        description: 'Additional Gradle options'
        required: false
        default: ''

jobs:
  release-test:
    name: Release Test

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1


    - name: Run Release Test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: 'releaseTest ${{ github.event.inputs.additionalGradleOptions }}'

    - name: Upload report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: reports
        path: build/reports/tests/releaseTest
        retention-days: 7
