name: Test workflow

on:
  workflow_dispatch:
    inputs:
      runSonarQubeScan:
        description: 'Run SonarQube scan'
        type: boolean

jobs:
  test:
  
    runs-on: ubuntu-latest
    env:
      SONART_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
    steps:

    - name: Print inputs
      run: echo "runSonarQubeScan = '${{ github.event.inputs.runSonarQubeScan }}'"

    - name: Build with Gradle
      run: echo "./gradlew build"

    - name: Run SonarQube scan
      if: github.event.inputs.runSonarQubeScan
      run: echo "./gradlew sonarqube"
