name: Test workflow

on:
  workflow_dispatch:
    inputs:
      runSonarQubeScan:
        description: 'Run SonarQube scan'
        type: boolean

jobs:
  test:
  
    runs-on: ubuntu-latest
    env:
      SONART_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
    steps:
    - name: Build with Gradle
      run: echo "build"
    - name: Run SonarQube scan
      run: echo "sonarqube"
      if: ${{ github.event.inputs.runSonarQubeScan }}
