name: Test workflow

on:
  workflow_dispatch:
    inputs:
      runSonarQubeScan:
        description: 'Run SonarQube scan'
        type: boolean
        default: 'true'

jobs:
  test:
  
    runs-on: ubuntu-latest
    env:
      SONART_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
    steps:
    - run: echo "Before ${{ github.event.inputs.runSonarQubeScan }} After"
  
