name: Test workflow

on:
  workflow_dispatch:
    inputs:
      additionalGradleOptions:
        description: 'Additional Gradle options'
        required: false
        default: ''

jobs:
  test:
  
    runs-on: ubuntu-latest
    env:
      SONART_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
    steps:

    - name: Print inputs
      run: echo "additionalGradleOptions = '${{ github.event.inputs.additionalGradleOptions }}'"

    - name: Build with Gradle
      run: echo "./gradlew build ${{ github.event.inputs.additionalGradleOptions }}"
